services:
  redis:
    image: redis:8.4.2
    ports:
      - "6379:6379"

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - api

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - BASE_URL=api
