services:
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

  nginx:
    restart: always
    image: adithyashenal/zephyr-nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - api

  api:
    image: adithyashenal/zephyr-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    image: adithyashenal/zephyr-frontend
    restart: unless-stopped

volumes:
  redis-data:
