name: Zephyr App Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t adithyashenal/zephyr-frontend ./frontend
          docker build -t adithyashenal/zephyr-nginx ./nginx
          docker build -t adithyashenal/zephyr-api ./backend

          docker push adithyashenal/zephyr-frontend
          docker push adithyashenal/zephyr-nginx
          docker push adithyashenal/zephyr-api
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/Zephyr-ChatApp
            git pull origin main
            docker compose pull
            docker compose up -d
            docker image prune -f
